### ISSUE TITLE
Publish docs to GitHub Pages

### ISSUE THREAD

**Issue by jelovirt** [cniweb/ant-contrib#1]
By moving [ant-contrib/docs/manual](https://github.com/cniweb/ant-contrib/tree/master/ant-contrib/docs/manual) to be `docs` folder on the root of the repository, [GitHub Pages] can publish the docs to https://cniweb.github.io/ant-contrib.

The docs should be cleaned, but the first step should be to publish them.

[GitHub Pages]: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch

**Comment by cniweb** [comment]
OK, thanks
I have it implemented:
https://cniweb.github.io/ant-contrib
